"""Add enhanced fields to Project model

Revision ID: ae41c65970a9
Revises: 7e8f40e38d8f
Create Date: 2025-09-09 01:11:16.321881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae41c65970a9'
down_revision: Union[str, None] = '7e8f40e38d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('project_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_metadata')
    op.drop_column('projects', 'tags')
    op.drop_column('projects', 'priority')
    # ### end Alembic commands ###